### ISSUE TITLE
Potential bug attempting to convert lists into dataframes

### ISSUE THREAD

**Issue by GodlikeRoy** [LyzandeR/RDota2#1]
Hello,

I have tried several methods to convert some of the lists returned via the get_* functions into data frames and multiple times have run into the error: "cannot coerce class ""dota+api"" to a data.frame". Here is a small sample of code that produces the error:

`MatchTest <- get_match_details(2790305415)`
`as.data.frame(MatchTest)`

`Error in as.data.frame.default(MatchTest) :` 
`    cannot coerce class ""dota_api"" to a data.frame`

I'm unsure if it's a matter of my code or whether it's a bug - I tried googling last night and found some more complex code for converting nested lists into dataframes and ran into the same error a few times. 

I think I could perhaps create data frames by extracting vectors from the list and compiling them together, but maybe this is a bug and there is an easier way. Thanks for looking into it again.

**Comment by LyzandeR** [comment]
Hi Roy,

Thanks a lot for posting it on github.

So, the problem is that you do not access just the `content` element of the `MatchTest` object. `MatchTest` consists of three elements:

* url - The Steam API url
* content - This is the content i.e. the data you are interested in
* response - This contains information about the request you made to steam like the full url, cookies, parameters (things usually people are not interested in)

If you type `MatchTest`  on your console `MatchTest$content` will be printed automatically (because this is what interests the user), but when you try to use `as.data.frame(MatchTest)` you are using it on the three elements described above which is why it fails.

The below will work:

```
MatchTest <- get_match_details(2790305415)
as.data.frame(MatchTest$content)
```

However, I would advise against converting the whole `MatchTest$content` into a data.frame since this massive nested list has multiple uneven (in terms of lengths) elements which means that `as.data.frame` will recycle them (all columns must have the same length in a data.frame) which might be misleading. Instead, consider `data.frame`-ing only the parts of the nested list that have the same number of elements or just use the nested list. Or maybe extract the players in one list and everything else in another. The vignette might help you as well, as it tries to show the structure of the output of each one of the functions:

[RDota2](https://cran.r-project.org/web/packages/RDota2/vignettes/RDota2.html)

Hope this solves your problem!

Theo

**Comment by GodlikeRoy** [comment]
Ahhh, that makes sense. Thanks for the swift reply!

Would you be able to suggest a way to get the data from the nested list into data frames, or should I try and work with the data in the current form?

My end goal is to be able to get the results of pro matches played by a subset of teams (I would probably manually specify which teams, the top 50 or so in the world perhaps) and the results and then make an ELO based system by ranking each player based on their results vs the opposing team (with the help of the PlayerRating packge most likely). It sounds like a herculean task given my rudimentary knowledge of R but you have to start somewhere right, and I think organising the data into the best format possible is probably my best place to start.

Thanks again for you help.

Roy

**Comment by LyzandeR** [comment]
Glad I could be of help :)

Basically, the way I would go about it is:

1. Work on just one match
2. Specify which categories / list elements I would like to extract
3. Use chaining `$` operators to extract those e.g. `MatchTest$content$players`.
4. Use `lapply` or `sapply` to iterate through lists and extract the parts that you like.

I think mastering the use of `lapply` or `sapply` is very important in automating data extraction from huge nested lists. There are a lot of tutorials online if you google something like "working with lapply and lists" that will guide you. It might seem like something difficult at the beginning but it will definitely pay off at some point.

Also, since this is a data manipulation question, if you find difficulty later on, consider posting a question on stackoverflow.com. People there are always willing to help out with such questions. Just add a small reproducible example of what you are trying to achieve and people will provide answers.

FInally, I wouldn't work with data.frames at all (or in most cases) since I have seen that for different matches Valve do not even provide a consistent structure of the lists. Quite often some of the elements will be missing which will cause errors if working with data.frames.

Hope this helps!

Theo
